### ISSUE TITLE
[Splash] The display Logo DOES NOT correct size.

### ISSUE THREAD

**Issue by at-cuongtruong** [queenscity/internship-2019-winter-App02#1]
**Enviroment**

- Samsung Galaxy A5(2016)
- Android  7.0

**Pre-Condition**

**Step to Perform**

1. Open [Demotrain] app.
2. Check UI of [Splash] screen.

**Actual Result**

At step 2: [Splash] screen is displayed as a PORTRAIT and displayed Logo in the central of screen with NOT correct size, Background is Black.

**Expected Result**

At step 2: [Splash] screen is displayed as a PORTRAIT and displayed Logo in the central of screen with correct size, Background is Black.

**Evidence**

![Ảnh chụp Màn hình 2020-02-25 lúc 8 35 57 SA](https://user-images.githubusercontent.com/59002145/75207034-401e3600-57aa-11ea-951c-9567dce7d790.png)

**Comment by at-huongle** [comment]
@at-cuongtruong 
bug này là size của logo không đúng hả em? hình em nhìn thấy nó sẽ to hơn so với hình trong spec phải không? 
Nêu là vậy thì hình này nó sẽ scale theo kích thước của màn hình và tuỳ thuộc vào device, vì vậy cái này không phải là bug nha

**Comment by at-cuongtruong** [comment]
DONE
