### ISSUE TITLE
[Examination / Quiz] Action of Back button is INCORRECT.

### ISSUE THREAD

**Issue by at-cuongtruong** [queenscity/internship-2019-winter-App02#18]
**Enviroment**

- Samsung Galaxy A5(2016)
- Android 7.0

**Pre-Condition**

[DM004_Examination]
1. Open [DM004_Examination] screen.
2. Registered user.
[DM005_Quiz]
1. Open [DM005_Quiz] screen.
2. Registered user.

**Step to perform**

[DM004_Examination]
[Case 1]

1. Tap on [Back] button.

[Case 2]

1. Tapping many times on [Back] button.

[DM005_Quiz]
[Case 3]

1. Tap on [Back] button.

[Case 4]

1. Tapping many times on [Back] button.

**Actual Result**

[DM004_Examination]
[Case 1]
At step 1:  Go to [DM001_Home] screen.
[Case 2]
At step 1: Catch event one-tap
At step 1: Go to [DM001_Home] screen.

[DM005_Quiz]
[Case 3]
At step 1:  Go to [DM001_Home] screen.
[Case 4]
At step 1: Catch event one-tap
At step 1: Go to [DM001_Home] screen.

**Expected Result**

[DM004_Examination]
[Case 1]
At step 1: Close [DM004_Examination] screen and Back to [DM001_Home] screen.
[Case 2]
At step 1: Catch event one-tap
At step 1: Close [DM004_Examination] screen and Back to [DM001_Home] screen.

[DM005_Quiz]
[Case 3]
At step 1: Close [DM005_Quiz] screen and Back to [DM001_Home] screen.
[Case 4]
At step 1: Catch event one-tap
At step 1: Close [DM005_Quiz] screen and Back to [DM001_Home] screen.

**Evidence**
[DM004_Examination]
https://drive.google.com/file/d/1nWV3HS1K0QL23EgWljNmxWDyLiRRhwza/view?usp=sharing
[DM005_Quiz]
https://drive.google.com/file/d/1RC6De2e0Nr_fNRlmv4j3dR8bkVVAw2td/view?usp=sharing

**Comment by at-huongle** [comment]
@at-cuongtruong em check lại bug này nha, rất khó hiểu chị không rõ bug ở đây là gì?
